version: '1'
services:
  nginx:
    image: nginx:latest
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/file-app/build:/usr/share/nginx/html
    container_name: nginx-proxy
    depends_on:
      - docker-server
  docker-server:
    build:
      context: ./backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: docker-server
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true